---
name: "Aritra"
surname: "Chatterjee"
position: "Sr.DataEngineering Analyst"
address: "Flat 403, Udaya Abhi's Residency, Kondapur, Hyderabad."
phone: +91 8017781327
profilepic: Aritra.jpg
email: "richie.chatterjee31@gmail.com"
github: richie312
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "A professional in the field of Machine Learning, API Development, Data Engineering and Devops with more than 9 years of experience."
output: vitae::twentyseconds
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Experience

 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.

# Education

```{r}
library(tibble)
tribble(
  ~ Company, ~ Year, ~ Skills, ~ Description,
  "Larsen & Toubro Infotech(S&P Global)", "2020-2021", "DataEngineering", "Planned, designed and implemented automated framework which takes json template as an input and applies transformation on dataset to generate the report in json which finally feeds the predefined tableau dashboard.",
  "CapitalNumbers Infotech", "2019-2020", "APIDevelopment", "Implemented Online Compiler for 14 different languages for inhouse project using sphere engine api, url creation (flask). Proper API Documentation(click on this link) using Rmarkdown/Swagger framework.",
  "GSPANN Technologies", "2019", "AWS|DataEngineering", "Build Data Pipeline for Google Analytics for client web application. Aws automation using boto3 with Python.",
  "Colt India Pvt. Ltd","2018", "R|MachineLearning", "Consulted the company on Customer Churn management in their network lease line connection business. Find out the main reasons for churn from multiple data source. Find out the spread of maximum churn location wise (Visual, network graph and leaflet). The work was confined to Descriptive and Predictive Analytics. Prescriptive Analytics was out of scope.",
  "Accenture India", "2012-2017","R|Python|ML|NLP", "Worked on Variour Projects associated with NLP, ML.Shiny Application Development.Flask Application Development.",
  "IBM GPS India","2011-2012", "ITIL", "Manage the infrastructure support team, multiple vendors, and Client. Delivery of agreed services to the client by utilizing Resource and Capabilities at an optimal level to maintain the ITIL standard aligned with Client requirement."
) %>% 
  detailed_entries( Company, Year, Skills, Description)
```

# Domain wise skill set

```{r}
library(tibble)
tribble(
  ~Domain, ~Skill,
  "Languages", "Python , R, Javascript, Markdown,Rmarkdown, Confluence Markup.",
  "Database", "SQL, MySQL and PostgreSQL, Teradata."
) %>% 
  brief_entries(
    Domain,Skill
  )
```

# Personal Projects

```{r}
library(tibble)
tribble(
  ~Project, ~Url,
  "JenkinsPipeline","http://jenkins-applyjob.nirvikalpa-projects.com:8080/",
  "API", "http://jenkins-applyjob.nirvikalpa-projects.com:8080/",
  "APIDocs","http://api.nirvikalpa-projects.com/docs",
  "ML Plaform", "",
  "Weather Application", ""
) %>% 
  brief_entries(
    Project, 
    Url
  )
```

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```

